source 'https://github.com/CocoaPods/Specs.git'

target 'HRSAdvancedTableViews', :exclusive => true do
  pod "HRSAdvancedTableViews", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HRSAdvancedTableViews", :path => "../"

  pod 'Expecta'
  pod 'OCMock'
end
