platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'HRSAdvancedTableViews' do
  pod "HRSAdvancedTableViews", :path => "../"
end

target 'Tests' do
  pod "HRSAdvancedTableViews", :path => "../"

  pod 'Expecta'
  pod 'OCMock'
end
